INSERT INTO phuong (ten_phuong, id_tinh) VALUES
('Phường Hoàn Kiếm', 1),
('Phường Cửa Nam', 1),
('Phường Ba Đình', 1),
('Phường Ngọc Hà', 1),
('Phường Giảng Võ', 1),
('Phường Hai Bà Trưng', 1),
('Phường Vĩnh Tuy', 1),
('Phường Bạch Mai', 1),
('Phường Đống Đa', 1),
('Phường Kim Liên', 1),
('Phường Văn Miếu - Quốc Tử Giám', 1),
('Phường Láng', 1),
('Phường Ô Chợ Dừa', 1),
('Phường Hồng Hà', 1),
('Phường Lĩnh Nam', 1),
('Phường Hoàng Mai', 1),
('Phường Vĩnh Hưng', 1),
('Phường Tương Mai', 1),
('Phường Định Công', 1),
('Phường Hoàng Liệt', 1),
('Phường Yên Sở', 1),
('Phường Thanh Xuân', 1),
('Phường Khương Đình', 1),
('Phường Phương Liệt', 1),
('Phường Cầu Giấy', 1),
('Phường Nghĩa Đô', 1),
('Phường Yên Hòa', 1),
('Phường Tây Hồ', 1),
('Phường Phú Thượng', 1),
('Phường Tây Tựu', 1),
('Phường Phú Diễn', 1),
('Phường Xuân Đỉnh', 1),
('Phường Đông Ngạc', 1),
('Phường Thượng Cát', 1),
('Phường Từ Liêm', 1),
('Phường Xuân Phương', 1),
('Phường Tây Mỗ', 1),
('Phường Đại Mỗ', 1),
('Phường Long Biên', 1),
('Phường Bồ Đề', 1),
('Phường Việt Hưng', 1),
('Phường Phúc Lợi', 1),
('Phường Hà Đông', 1),
('Phường Dương Nội', 1),
('Phường Yên Nghĩa', 1),
('Phường Phú Lương', 1),
('Phường Kiến Hưng', 1),
('Xã Thanh Trì', 1),
('Xã Đại Thanh', 1),
('Xã Nam Phù', 1),
('Xã Ngọc Hồi', 1),
('Phường Thanh Liệt', 1),
('Xã Thượng Phúc', 1),
('Xã Thường Tín', 1),
('Xã Chương Dương', 1),
('Xã Hồng Vân', 1),
('Xã Phú Xuyên', 1),
('Xã Phượng Dực', 1),
('Xã Chuyên Mỹ', 1),
('Xã Đại Xuyên', 1),
('Xã Thanh Oai', 1),
('Xã Bình Minh', 1),
('Xã Tam Hưng', 1),
('Xã Dân Hòa', 1),
('Xã Vân Đình', 1),
('Xã Ứng Thiên', 1),
('Xã Hòa Xá', 1),
('Xã Ứng Hòa', 1),
('Xã Mỹ Đức', 1),
('Xã Hồng Sơn', 1),
('Xã Phúc Sơn', 1),
('Xã Hương Sơn', 1),
('Phường Chương Mỹ', 1),
('Xã Phú Nghĩa', 1),
('Xã Xuân Mai', 1),
('Xã Trần Phú', 1),
('Xã Hòa Phú', 1),
('Xã Quảng Bị', 1),
('Xã Minh Châu', 1),
('Xã Quảng Oai', 1),
('Xã Vật Lại', 1),
('Xã Cổ Đô', 1),
('Xã Bất Bạt', 1),
('Xã Suối Hai', 1),
('Xã Ba Vì', 1),
('Xã Yên Bài', 1),
('Phường Sơn Tây', 1),
('Phường Tùng Thiện', 1),
('Xã Đoài Phương', 1),
('Xã Phúc Thọ', 1),
('Xã Phúc Lộc', 1),
('Xã Hát Môn', 1),
('Xã Thạch Thất', 1),
('Xã Hạ Bằng', 1),
('Xã Tây Phương', 1),
('Xã Hòa Lạc', 1),
('Xã Yên Xuân', 1),
('Xã Quốc Oai', 1),
('Xã Hưng Đạo', 1),
('Xã Kiều Phú', 1),
('Xã Phú Cát', 1),
('Xã Hoài Đức', 1),
('Xã Dương Hòa', 1),
('Xã Sơn Đồng', 1),
('Xã An Khánh', 1),
('Xã Đan Phượng', 1),
('Xã Ô Diên', 1),
('Xã Liên Minh', 1),
('Xã Gia Lâm', 1),
('Xã Thuận An', 1),
('Xã Bát Tràng', 1),
('Xã Phù Đổng', 1),
('Xã Thư Lâm', 1),
('Xã Đông Anh', 1),
('Xã Phúc Thịnh', 1),
('Xã Thiên Lộc', 1),
('Xã Vĩnh Thanh', 1),
('Xã Mê Linh', 1),
('Xã Yên Lãng', 1),
('Xã Tiến Thắng', 1),
('Xã Quang Minh', 1),
('Xã Sóc Sơn', 1),
('Xã Đa Phúc', 1),
('Xã Nội Bài', 1),
('Xã Trung Giã', 1),
('Xã Kim Anh', 1),
('Xã Đại Sơn', 2),
('Xã Sơn Động', 2),
('Xã Tây Yên Tử', 2),
('Xã Dương Hưu', 2),
('Xã Yên Định', 2),
('Xã An Lạc', 2),
('Xã Vân Sơn', 2),
('Xã Biển Động', 2),
('Xã Lục Ngạn', 2),
('Xã Đèo Gia', 2),
('Xã Sơn Hải', 2),
('Xã Tân Sơn', 2),
('Phường Phượng Sơn', 2),
('Xã Lục Sơn', 2),
('Xã Trường Sơn', 2),
('Xã Cẩm Lý', 2),
('Xã Đông Phú', 2),
('Xã Nghĩa Phương', 2),
('Xã Lục Nam', 2),
('Xã Bắc Lũng', 2),
('Xã Bảo Đài', 2),
('Xã Lạng Giang', 2),
('Xã Mỹ Thái', 2),
('Xã Kép', 2),
('Xã Tân Dĩnh', 2),
('Xã Tiên Lục', 2),
('Xã Yên Thế', 2),
('Xã Bố Hạ', 2),
('Xã Đồng Kỳ', 2),
('Xã Xuân Lương', 2),
('Xã Tam Tiến', 2),
('Xã Tân Yên', 2),
('Xã Ngọc Thiện', 2),
('Xã Nhã Nam', 2),
('Xã Phúc Hòa', 2),
('Phường Tự Lạn', 2),
('Phường Việt Yên', 2),
('Phường Nếnh', 2),
('Phường Vân Hà', 2),
('Xã Đồng Việt', 2),
('Phường Tân Tiến', 2),
('Phường Cảnh Thụy', 2),
('Phường Kinh Bắc', 2),
('Phường Võ Cường', 2),
('Phường Vũ Ninh', 2),
('Phường Hạp Lĩnh', 2),
('Phường Nam Sơn', 2),
('Phường Từ Sơn', 2),
('Phường Tam Sơn', 2),
('Phường Đồng Nguyên', 2),
('Phường Phù Khê', 2),
('Phường Thuận Thành', 2),
('Phường Mão Điền', 2),
('Phường Trạm Lộ', 2),
('Phường Trí Quả', 2),
('Phường Song Liễu', 2),
('Phường Ninh Xá', 2),
('Phường Quế Võ', 2),
('Phường Phương Liễu', 2),
('Phường Nhân Hòa', 2),
('Phường Đào Viên', 2),
('Phường Bồng Lai', 2),
('Xã Chi Lăng', 2),
('Xã Phật Tích', 2),
('Xã Gia Bình', 2),
('Xã Nhân Thắng', 2),
('Xã Đại Lai', 2),
('Xã Cao Đức', 2),
('Xã Đông Cứu', 2),
('Xã Lương Tài', 2),
('Xã Lâm Thao', 2),
('Xã Trung Chính', 2),
('Xã Trung Kênh', 2),
('Xã Tuấn Đạo', 2),
('Phường An Sinh', 3),
('Phường Đông Triều', 3),
('Phường Bình Khê', 3),
('Phường Mạo Khê', 3),
('Phường Hoàng Quế', 3),
('Phường Yên Tử', 3),
('Phường Vàng Danh', 3),
('Phường Uông Bí', 3),
('Phường Đông Mai', 3),
('Phường Hiệp Hòa', 3),
('Phường Quảng Yên', 3),
('Phường Hà An', 3),
('Phường Phong Cốc', 3),
('Phường Liên Hòa', 3),
('Phường Tuần Châu', 3),
('Phường Việt Hưng', 3),
('Phường Bãi Cháy', 3),
('Phường Hà Tu', 3),
('Phường Hà Lầm', 3),
('Phường Cao Xanh', 3),
('Phường Hồng Gai', 3),
('Phường Hạ Long', 3),
('Phường Hoành Bồ', 3),
('Xã Quảng La', 3),
('Xã Thống Nhất', 3),
('Phường Mông Dương', 3),
('Phường Quang Hanh', 3),
('Phường Cẩm Phả', 3),
('Phường Cửa Ông', 3),
('Xã Hải Hòa', 3),
('Xã Tiên Yên', 3),
('Xã Điền Xá', 3),
('Xã Đông Ngũ', 3),
('Xã Hải Lạng', 3),
('Xã Lương Minh', 3),
('Xã Kỳ Thượng', 3),
('Xã Ba Chẽ', 3),
('Xã Quảng Tân', 3),
('Xã Đầm Hà', 3),
('Xã Quảng Hà', 3),
('Xã Đường Hoa', 3),
('Xã Quảng Đức', 3),
('Xã Hoành Mô', 3),
('Xã Lục Hồn', 3),
('Xã Bình Liêu', 3),
('Xã Hải Sơn', 3),
('Xã Hải Ninh', 3),
('Xã Vĩnh Thực', 3),
('Phường Móng Cái 1', 3),
('Phường Móng Cái 2', 3),
('Phường Móng Cái 3', 3),
('Đặc khu Vân Đồn', 3),
('Đặc khu Cô Tô', 3),
('Xã Cái Chiên', 3),
('Phường Thuỷ Nguyên', 4),
('Phường Thiên Hương', 4),
('Phường Hoà Bình', 4),
('Phường Nam Triệu', 4),
('Phường Bạch Đằng', 4),
('Phường Lưu Kiếm', 4),
('Phường Lê Ích Mộc', 4),
('Phường Hồng Bàng', 4),
('Phường Hồng An', 4),
('Phường Ngô Quyền', 4),
('Phường Gia Viên', 4),
('Phường Lê Chân', 4),
('Phường An Biên', 4),
('Phường Hải An', 4),
('Phường Đông Hải', 4),
('Phường Hưng Đạo', 4),
('Phường Dương Kinh', 4),
('Phường An Dương', 4),
('Phường An Hải', 4),
('Phường An Phong', 4),
('Xã An Hưng', 4),
('Xã An Khánh', 4),
('Xã An Quang', 4),
('Xã An Trường', 4),
('Xã An Lão', 4),
('Xã Kiến Thụy', 4),
('Xã Kiến Minh', 4),
('Xã Kiến Hải', 4),
('Xã Kiến Hưng', 4),
('Xã Nghi Dương', 4),
('Xã Quyết Thắng', 4),
('Xã Tiên Lãng', 4),
('Xã Tân Minh', 4),
('Xã Tiên Minh', 4),
('Xã Chấn Hưng', 4),
('Xã Hùng Thắng', 4),
('Xã Vĩnh Bảo', 4),
('Xã Nguyễn Bỉnh Khiêm', 4),
('Xã Vĩnh Am', 4),
('Xã Vĩnh Hải', 4),
('Xã Vĩnh Hòa', 4),
('Xã Vĩnh Thịnh', 4),
('Xã Vĩnh Thuận', 4),
('Xã Việt Khê', 4),
('Đặc khu Cát Hải', 4),
('Đặc khu Bạch Long Vĩ', 4),
('Phường Hải Dương', 4),
('Phường Lê Thanh Nghị', 4),
('Phường Việt Hòa', 4),
('Phường Thành Đông', 4),
('Phường Nam Đồng', 4),
('Phường Tân Hưng', 4),
('Phường Thạch Khôi', 4),
('Phường Tứ Minh', 4),
('Phường Ái Quốc', 4),
('Phường Chu Văn An', 4),
('Phường Chí Linh', 4),
('Phường Trần Hưng Đạo', 4),
('Phường Nguyễn Trãi', 4),
('Phường Trần Nhân Tông', 4),
('Phường Lê Đại Hành', 4),
('Phường Kinh Môn', 4),
('Phường Nguyễn Đại Năng', 4),
('Phường Trần Liễu', 4),
('Phường Bắc An Phụ', 4),
('Phường Phạm Sư Mạnh', 4),
('Phường Nhị Chiểu', 4),
('Xã Nam An Phụ', 4),
('Xã Nam Sách', 4),
('Xã Thái Tân', 4),
('Xã Hợp Tiến', 4),
('Xã Trần Phú', 4),
('Xã An Phú', 4),
('Xã Thanh Hà', 4),
('Xã Hà Tây', 4),
('Xã Hà Bắc', 4),
('Xã Hà Nam', 4),
('Xã Hà Đông', 4),
('Xã Cẩm Giang', 4),
('Xã Tuệ Tĩnh', 4),
('Xã Mao Điền', 4),
('Xã Cẩm Giàng', 4),
('Xã Kẻ Sặt', 4),
('Xã Bình Giang', 4),
('Xã Đường An', 4),
('Xã Thượng Hồng', 4),
('Xã Gia Lộc', 4),
('Xã Yết Kiêu', 4),
('Xã Gia Phúc', 4),
('Xã Trường Tân', 4),
('Xã Tứ Kỳ', 4),
('Xã Tân Kỳ', 4),
('Xã Đại Sơn', 4),
('Xã Chí Minh', 4),
('Xã Lạc Phượng', 4),
('Xã Hồng Châu', 4),
('Xã Thanh Miện', 4),
('Xã Bắc Thanh Miện', 4),
('Xã Hải Hưng', 4),
('Xã Nguyễn Lương Bằng', 4),
('Xã Nam Thanh Miện', 4),
('Xã Phú Thái', 4),
('Xã Lai Khê', 4),
('Xã An Thành', 4),
('Xã Kim Thành', 4),
('Phường Phố Hiến', 5),
('Phường Sơn Nam', 5),
('Phường Hồng Châu', 5),
('Phường Mỹ Hào', 5),
('Phường Đường Hào', 5),
('Phường Thượng Hồng', 5),
('Xã Tân Hưng', 5),
('Xã Hoàng Hoa Thám', 5),
('Xã Tiên Lữ', 5),
('Xã Lương Bằng', 5),
('Xã Nghĩa Dân', 5),
('Xã Hiệp Cường', 5),
('Xã Đức Hợp', 5),
('Xã Ân Thi', 5),
('Xã Xuân Trúc', 5),
('Xã Phạm Ngũ Lão', 5),
('Xã Nguyễn Trãi', 5),
('Phường Trà Lý', 5),
('Phường Vũ Phúc', 5),
('Xã Thái Thụy', 5),
('Xã Đông Thụy Anh', 5),
('Xã Bắc Thụy Anh', 5),
('Xã Nam Thái Ninh', 5),
('Xã Tây Thái Ninh', 5),
('Xã Tây Thụy Anh', 5),
('Xã Nguyễn Du', 5),
('Xã Quỳnh An', 5),
('Xã Ngọc Lâm', 5),
('Xã Đồng Bằng', 5),
('Xã A Sào', 5),
('Xã Phụ Dực', 5),
('Xã Tân Tiến', 5),
('Xã Hưng Hà', 5),
('Xã Tiên La', 5),
('Xã Lê Quý Đôn', 5),
('Xã Kiến Xương', 5),
('Xã Quang Lịch', 5),
('Xã Vũ Quý', 5),
('Xã Vạn Xuân', 5),
('Xã Gia Viễn', 6),
('Xã Đại Hoàng', 6),
('Xã Gia Hưng', 6),
('Xã Gia Tường', 6),
('Xã Phú Sơn', 6),
('Xã Cúc Phương', 6),
('Xã Phú Long', 6),
('Xã Thanh Sơn', 6),
('Xã Chất Bình', 6),
('Xã Kim Sơn', 6),
('Xã Quang Thiện', 6),
('Xã Phát Diệm', 6),
('Xã Lai Thành', 6),
('Xã Định Hóa', 6),
('Xã Bình Minh', 6),
('Xã Kim Đông', 6),
('Xã Liêm Hà', 6),
('Xã Tân Thanh', 6),
('Xã Thanh Bình', 6),
('Xã Thanh Lâm', 6),
('Xã Thanh Liêm', 6),
('Xã Liên Minh', 6),
('Xã Ý Yên', 6),
('Xã Yên Đồng', 6),
('Xã Yên Cường', 6),
('Xã Vạn Thắng', 6),
('Xã Vũ Dương', 6),
('Xã Tân Minh', 6),
('Xã Phong Doanh', 6),
('Xã Xuân Hồng', 6),
('Xã Hải Hậu', 6),
('Xã Hải Anh', 6),
('Xã Hải Tiến', 6),
('Xã Hải Hưng', 6),
('Xã Quỹ Nhất', 6),
('Xã Nghĩa Lâm', 6),
('Xã Rạng Đông', 6),
('Phường Tây Hoa Lư', 6),
('Phường Hoa Lư', 6),
('Phường Nam Hoa Lư', 6),
('Phường Đông Hoa Lư', 6),
('Phường Tam Điệp', 6),
('Phường Yên Sơn', 6),
('Phường Trung Sơn', 6),
('Phường Yên Thắng', 6),
('Phường Hà Nam', 6),
('Phường Phủ Lý', 6),
('Phường Phù Vân', 6),
('Phường Châu Sơn', 6),
('Phường Liêm Tuyền', 6),
('Phường Duy Tiên', 6),
('Phường Duy Tân', 6),
('Phường Lý Thường Kiệt', 6),
('Phường Kim Thanh', 6),
('Phường Tam Chúc', 6),
('Phường Kim Bảng', 6),
('Phường Nam Định', 6),
('Phường Thiên Trường', 6),
('Phường Đông A', 6),
('Phường Vị Khê', 6),
('Phường Thành Nam', 6),
('Phường Trường Thi', 6),
('Phường Hồng Quang', 6),
('Phường Mỹ Lộc', 6),
('Phường Thục Phán', 7),
('Phường Nùng Trí Cao', 7),
('Phường Tân Giang', 7),
('Xã Quảng Lâm', 7),
('Xã Nam Quang', 7),
('Xã Lý Bôn', 7),
('Xã Bảo Lâm', 7),
('Xã Yên Thổ', 7),
('Xã Sơn Lộ', 7),
('Xã Hưng Đạo', 7),
('Xã Bảo Lạc', 7),
('Xã Cốc Pàng', 7),
('Xã Cô Ba', 7),
('Xã Khánh Xuân', 7),
('Xã Xuân Trường', 7),
('Xã Huy Giáp', 7),
('Xã Ca Thành', 7),
('Xã Phan Thanh', 7),
('Xã Thành Công', 7),
('Xã Tĩnh Túc', 7),
('Xã Tam Kim', 7),
('Xã Nguyên Bình', 7),
('Xã Minh Tâm', 7),
('Xã Thanh Long', 7),
('Xã Cần Yên', 7),
('Xã Thông Nông', 7),
('Xã Trường Hà', 7),
('Xã Hà Quảng', 7),
('Xã Lũng Nặm', 7),
('Xã Tổng Cọt', 7),
('Xã Nam Tuấn', 7),
('Xã Hòa An', 7),
('Xã Bạch Đằng', 7),
('Xã Nguyễn Huệ', 7),
('Xã Minh Khai', 7),
('Xã Canh Tân', 7),
('Xã Kim Đồng', 7),
('Xã Thạch An', 7),
('Xã Đông Khê', 7),
('Xã Đức Long', 7),
('Xã Phục Hòa', 7),
('Xã Bế Văn Đàn', 7),
('Xã Độc Lập', 7),
('Xã Quảng Uyên', 7),
('Xã Hạnh Phúc', 7),
('Xã Quang Hán', 7),
('Xã Trà Lĩnh', 7),
('Xã Quang Trung', 7),
('Xã Đoài Dương', 7),
('Xã Trùng Khánh', 7),
('Xã Đàm Thuỷ', 7),
('Xã Đình Phong', 7),
('Xã Lý Quốc', 7),
('Xã Hạ Lang', 7),
('Xã Vinh Quý', 7),
('Xã Quang Long', 7),
('Xã Thượng Lâm', 8),
('Xã Lâm Bình', 8),
('Xã Thượng Nông', 8),
('Xã Hồng Thái', 8),
('Xã Nà Hang', 8),
('Xã Tân Mỹ', 8),
('Xã Yên Lập', 8),
('Xã Tân An', 8),
('Xã Chiêm Hoá', 8),
('Xã Hoà An', 8),
('Xã Kiên Đài', 8),
('Xã Tri Phú', 8),
('Xã Kim Bình', 8),
('Xã Yên Nguyên', 8),
('Xã Trung Hà', 8),
('Xã Yên Phú', 8),
('Xã Bạch Xa', 8),
('Xã Phù Lưu', 8),
('Xã Hàm Yên', 8),
('Xã Bình Xa', 8),
('Xã Thái Sơn', 8),
('Xã Thái Hoà', 8),
('Xã Tân Long', 8),
('Xã Xuân Vân', 8),
('Xã Lực Hành', 8),
('Xã Yên Sơn', 8),
('Xã Nhữ Khê', 8),
('Xã Kiến Thiết', 8),
('Xã Tân Trào', 8),
('Xã Minh Thanh', 8),
('Xã Sơn Dương', 8),
('Xã Bình Ca', 8),
('Xã Tân Thanh', 8),
('Xã Sơn Thuỷ', 8),
('Xã Phú Lương', 8),
('Xã Trường Sinh', 8),
('Xã Hồng Sơn', 8),
('Xã Đông Thọ', 8),
('Phường Bình Thuận', 8),
('Xã Lũng Cú', 8),
('Xã Đồng Văn', 8),
('Xã Sà Phìn', 8),
('Xã Phố Bảng', 8),
('Xã Lũng Phìn', 8),
('Xã Sủng Máng', 8),
('Xã Sơn Vĩ', 8),
('Xã Mèo Vạc', 8),
('Xã Khâu Vai', 8),
('Xã Niêm Sơn', 8),
('Xã Tát Ngà', 8),
('Xã Thắng Mố', 8),
('Xã Bạch Đích', 8),
('Xã Yên Minh', 8),
('Xã Mậu Duệ', 8),
('Xã Ngọc Long', 8),
('Xã Du Già', 8),
('Xã Đường Thượng', 8),
('Xã Lùng Tám', 8),
('Xã Cán Tỷ', 8),
('Xã Nghĩa Thuận', 8),
('Xã Quản Bạ', 8),
('Xã Tùng Vài', 8),
('Xã Yên Cường', 8),
('Xã Đường Hồng', 8),
('Xã Bắc Mê', 8),
('Xã Giáp Trung', 8),
('Xã Minh Sơn', 8),
('Xã Minh Ngọc', 8),
('Xã Ngọc Đường', 8),
('Phường Hà Giang 1', 8),
('Phường Hà Giang 2', 8),
('Xã Lao Chải', 8),
('Xã Thanh Thuỷ', 8),
('Xã Minh Tân', 8),
('Xã Thuận Hoà', 8),
('Xã Tùng Bá', 8),
('Xã Phú Linh', 8),
('Xã Linh Hồ', 8),
('Xã Bạch Ngọc', 8),
('Xã Vị Xuyên', 8),
('Xã Việt Lâm', 8),
('Xã Cao Bồ', 8),
('Xã Thượng Sơn', 8),
('Xã Tân Quang', 8),
('Xã Đồng Tâm', 8),
('Xã Liên Hiệp', 8),
('Xã Bằng Hành', 8),
('Xã Bắc Quang', 8),
('Xã Hùng An', 8),
('Xã Vĩnh Tuy', 8),
('Xã Đồng Yên', 8),
('Xã Tiên Yên', 8),
('Xã Xuân Giang', 8),
('Xã Bằng Lang', 8),
('Xã Yên Thành', 8),
('Xã Quang Bình', 8),
('Xã Tân Trịnh', 8),
('Xã Tiên Nguyên', 8),
('Xã Thông Nguyên', 8),
('Xã Hồ Thầu', 8),
('Xã Nậm Dịch', 8),
('Xã Tân Tiến', 8),
('Xã Hoàng Su Phì', 8),
('Xã Thàng Tín', 8),
('Xã Bản Máy', 8),
('Xã Pờ Ly Ngài', 8),
('Xã Xín Mần', 8),
('Xã Pà Vầy Sủ', 8),
('Xã Nấm Dẩn', 8),
('Xã Trung Thịnh', 8),
('Xã Quảng Nguyên', 8),
('Xã Khuôn Lùng', 8),
('Xã Khao Mang', 9),
('Xã Mù Cang Chải', 9),
('Xã Púng Luông', 9),
('Xã Tú Lệ', 9),
('Xã Trạm Tấu', 9),
('Xã Hạnh Phúc', 9),
('Xã Phình Hồ', 9),
('Phường Nghĩa Lộ', 9),
('Phường Trung Tâm', 9),
('Phường Cầu Thia', 9),
('Xã Liên Sơn', 9),
('Xã Gia Hội', 9),
('Xã Sơn Lương', 9),
('Xã Thượng Bằng La', 9),
('Xã Chấn Thịnh', 9),
('Xã Nghĩa Tâm', 9),
('Xã Văn Chấn', 9),
('Xã Mậu A', 9),
('Xã Xuân Ái', 9),
('Xã Mỏ Vàng', 9),
('Xã Lâm Thượng', 9),
('Xã Lục Yên', 9),
('Xã Tân Lĩnh', 9),
('Xã Khánh Hòa', 9),
('Xã Phúc Lợi', 9),
('Xã Mường Lai', 9),
('Xã Cảm Nhân', 9),
('Xã Yên Thành', 9),
('Xã Thác Bà', 9),
('Xã Yên Bình', 9),
('Xã Bảo Ái', 9),
('Phường Văn Phú', 9),
('Phường Yên Bái', 9),
('Phường Nam Cường', 9),
('Phường Âu Lâu', 9),
('Xã Trấn Yên', 9),
('Xã Hưng Khánh', 9),
('Xã Lương Thịnh', 9),
('Xã Việt Hồng', 9),
('Xã Quy Mông', 9),
('Xã Phong Hải', 9),
('Xã Xuân Quang', 9),
('Xã Bảo Thắng', 9),
('Xã Tằng Lỏong', 9),
('Xã Gia Phú', 9),
('Xã Cốc San', 9),
('Xã Hợp Thành', 9),
('Phường Cam Đường', 9),
('Phường Lào Cai', 9),
('Xã Mường Hum', 9),
('Xã Dền Sáng', 9),
('Xã Y Tý', 9),
('Xã A Mú Sung', 9),
('Xã Trịnh Tường', 9),
('Xã Bản Xèo', 9),
('Xã Bát Xát', 9),
('Xã Nghĩa Đô', 9),
('Xã Thượng Hà', 9),
('Xã Bảo Yên', 9),
('Xã Xuân Hòa', 9),
('Xã Phúc Khánh', 9),
('Xã Bảo Hà', 9),
('Xã Võ Lao', 9),
('Xã Khánh Yên', 9),
('Xã Văn Bàn', 9),
('Xã Dương Quỳ', 9),
('Xã Chiềng Ken', 9),
('Xã Minh Lương', 9),
('Xã Nậm Chày', 9),
('Xã Mường Bo', 9),
('Xã Bản Hồ', 9),
('Xã Tả Phìn', 9),
('Xã Tả Van', 9),
('Phường Sa Pa', 9),
('Xã Cốc Lầu', 9),
('Xã Bảo Nhai', 9),
('Xã Bản Liền', 9),
('Xã Bắc Hà', 9),
('Xã Tả Củ Tỷ', 9),
('Xã Lùng Phình', 9),
('Xã Pha Long', 9),
('Xã Mường Khương', 9),
('Xã Bản Lầu', 9),
('Xã Cao Sơn', 9),
('Xã Si Ma Cai', 9),
('Xã Sín Chéng', 9),
('Xã Lao Chải', 9),
('Xã Chế Tạo', 9),
('Xã Nậm Có', 9),
('Xã Tà Xi Láng', 9),
('Xã Phong Dụ Thượng', 9),
('Xã Cát Thịnh', 9),
('Xã Nậm Xé', 9),
('Xã Ngũ Chỉ Sơn', 9),
('Phường Phan Đình Phùng', 10),
('Phường Linh Sơn', 10),
('Phường Tích Lương', 10),
('Phường Gia Sàng', 10),
('Phường Quyết Thắng', 10),
('Phường Quan Triều', 10),
('Xã Tân Cương', 10),
('Xã Đại Phúc', 10),
('Xã Đại Từ', 10),
('Xã Đức Lương', 10),
('Xã Phú Thịnh', 10),
('Xã La Bằng', 10),
('Xã Phú Lạc', 10),
('Xã An Khánh', 10),
('Xã Quân Chu', 10),
('Xã Vạn Phú', 10),
('Xã Phú Xuyên', 10),
('Phường Phổ Yên', 10),
('Phường Vạn Xuân', 10),
('Phường Trung Thành', 10),
('Phường Phúc Thuận', 10),
('Xã Thành Công', 10),
('Xã Phú Bình', 10),
('Xã Tân Thành', 10),
('Xã Điềm Thụy', 10),
('Xã Kha Sơn', 10),
('Xã Tân Khánh', 10),
('Xã Đồng Hỷ', 10),
('Xã Quang Sơn', 10),
('Xã Trại Cau', 10),
('Xã Nam Hòa', 10),
('Xã Văn Hán', 10),
('Xã Văn Lăng', 10),
('Phường Sông Công', 10),
('Phường Bá Xuyên', 10),
('Phường Bách Quang', 10),
('Xã Phú Lương', 10),
('Xã Vô Tranh', 10),
('Xã Yên Trạch', 10),
('Xã Hợp Thành', 10),
('Xã Định Hóa', 10),
('Xã Bình Yên', 10),
('Xã Trung Hội', 10),
('Xã Phượng Tiến', 10),
('Xã Phú Đình', 10),
('Xã Bình Thành', 10),
('Xã Kim Phượng', 10),
('Xã Lam Vỹ', 10),
('Xã Võ Nhai', 10),
('Xã Dân Tiến', 10),
('Xã Nghinh Tường', 10),
('Xã Thần Sa', 10),
('Xã La Hiên', 10),
('Xã Tràng Xá', 10),
('Xã Bằng Thành', 10),
('Xã Nghiên Loan', 10),
('Xã Cao Minh', 10),
('Xã Ba Bể', 10),
('Xã Chợ Rã', 10),
('Xã Phúc Lộc', 10),
('Xã Thượng Minh', 10),
('Xã Đồng Phúc', 10),
('Xã Yên Bình', 10),
('Xã Bằng Vân', 10),
('Xã Ngân Sơn', 10),
('Xã Nà Phặc', 10),
('Xã Hiệp Lực', 10),
('Xã Nam Cường', 10),
('Xã Quảng Bạch', 10),
('Xã Yên Thịnh', 10),
('Xã Chợ Đồn', 10),
('Xã Yên Phong', 10),
('Xã Nghĩa Tá', 10),
('Xã Phủ Thông', 10),
('Xã Cẩm Giàng', 10),
('Xã Vĩnh Thông', 10),
('Xã Bạch Thông', 10),
('Xã Phong Quang', 10),
('Phường Đức Xuân', 10),
('Phường Bắc Kạn', 10),
('Xã Văn Lang', 10),
('Xã Cường Lợi', 10),
('Xã Na Rì', 10),
('Xã Trần Phú', 10),
('Xã Côn Minh', 10),
('Xã Xuân Dương', 10),
('Xã Tân Kỳ', 10),
('Xã Thanh Mai', 10),
('Xã Thanh Thịnh', 10),
('Xã Chợ Mới', 10),
('Xã Sảng Mộc', 10),
('Xã Thượng Quan', 10),
('Xã Thất Khê', 11),
('Xã Đoàn Kết', 11),
('Xã Tân Tiến', 11),
('Xã Tràng Định', 11),
('Xã Quốc Khánh', 11),
('Xã Kháng Chiến', 11),
('Xã Quốc Việt', 11),
('Xã Bình Gia', 11),
('Xã Tân Văn', 11),
('Xã Hồng Phong', 11),
('Xã Hoa Thám', 11),
('Xã Quý Hòa', 11),
('Xã Thiện Hòa', 11),
('Xã Thiện Thuật', 11),
('Xã Thiện Long', 11),
('Xã Bắc Sơn', 11),
('Xã Hưng Vũ', 11),
('Xã Vũ Lăng', 11),
('Xã Nhất Hòa', 11),
('Xã Vũ Lễ', 11),
('Xã Tân Tri', 11),
('Xã Văn Quan', 11),
('Xã Điềm He', 11),
('Xã Tri Lễ', 11),
('Xã Yên Phúc', 11),
('Xã Tân Đoàn', 11),
('Xã Khánh Khê', 11),
('Xã Na Sầm', 11),
('Xã Văn Lãng', 11),
('Xã Hội Hoan', 11),
('Xã Thụy Hùng', 11),
('Xã Tân Thanh', 11),
('Xã Lộc Bình', 11),
('Xã Mẫu Sơn', 11),
('Xã Na Dương', 11),
('Xã Lợi Bác', 11),
('Xã Thống Nhất', 11),
('Xã Xuân Dương', 11),
('Xã Khuất Xá', 11),
('Xã Đình Lập', 11),
('Xã Châu Sơn', 11),
('Xã Kiên Mộc', 11),
('Xã Thái Bình', 11),
('Xã Hữu Lũng', 11),
('Xã Tuấn Sơn', 11),
('Xã Tân Thành', 11),
('Xã Vân Nham', 11),
('Xã Thiện Tân', 11),
('Xã Yên Bình', 11),
('Xã Hữu Liên', 11),
('Xã Cai Kinh', 11),
('Xã Chi Lăng', 11),
('Xã Nhân Lý', 11),
('Xã Chiến Thắng', 11),
('Xã Quan Sơn', 11),
('Xã Bằng Mạc', 11),
('Xã Vạn Linh', 11),
('Xã Đồng Đăng', 11),
('Xã Cao Lộc', 11),
('Xã Công Sơn', 11),
('Xã Ba Sơn', 11),
('Phường Tam Thanh', 11),
('Phường Lương Văn Tri', 11),
('Phường Hoàng Văn Thụ', 11),
('Phường Đông Kinh', 11),
('Phường Việt Trì', 12),
('Phường Nông Trang', 12),
('Phường Thanh Miếu', 12),
('Phường Vân Phú', 12),
('Xã Hy Cương', 12),
('Phường Phú Thọ', 12),
('Phường Âu Cơ', 12),
('Xã Phù Ninh', 12),
('Xã Dân Chủ', 12),
('Xã Phú Mỹ', 12),
('Xã Trạm Thản', 12),
('Xã Bình Phú', 12),
('Xã Thanh Ba', 12),
('Xã Quảng Yên', 12),
('Xã Hoàng Cương', 12),
('Xã Đông Thành', 12),
('Xã Chí Tiên', 12),
('Xã Liên Minh', 12),
('Xã Đoan Hùng', 12),
('Xã Tây Cốc', 12),
('Xã Chân Mộng', 12),
('Xã Chí Đám', 12),
('Xã Bằng Luân', 12),
('Xã Hạ Hòa', 12),
('Xã Đan Thượng', 12),
('Xã Yên Kỳ', 12),
('Xã Vĩnh Chân', 12),
('Xã Văn Lang', 12),
('Xã Hiền Lương', 12),
('Xã Cẩm Khê', 12),
('Xã Phú Khê', 12),
('Xã Hùng Việt', 12),
('Xã Đồng Lương', 12),
('Xã Tiên Lương', 12),
('Xã Vân Bán', 12),
('Xã Tam Nông', 12),
('Xã Thọ Văn', 12),
('Xã Vạn Xuân', 12),
('Xã Hiền Quan', 12),
('Xã Thanh Thuỷ', 12),
('Xã Đào Xá', 12),
('Xã Tu Vũ', 12),
('Xã Thanh Sơn', 12),
('Xã Võ Miếu', 12),
('Xã Văn Miếu', 12),
('Xã Cự Đồng', 12),
('Xã Hương Cần', 12),
('Xã Yên Sơn', 12),
('Xã Khả Cửu', 12),
('Xã Tân Sơn', 12),
('Xã Minh Đài', 12),
('Xã Lai Đồng', 12),
('Xã Thu Cúc', 12),
('Xã Xuân Đài', 12),
('Xã Long Cốc', 12),
('Xã Yên Lập', 12),
('Xã Thượng Long', 12),
('Xã Sơn Lương', 12),
('Xã Xuân Viên', 12),
('Xã Minh Hòa', 12),
('Xã Trung Sơn', 12),
('Xã Tam Sơn', 12),
('Xã Sông Lô', 12),
('Xã Hải Lựu', 12),
('Xã Yên Lãng', 12),
('Xã Lập Thạch', 12),
('Xã Tiên Lữ', 12),
('Xã Đạo Trù', 12),
('Xã Tam Dương', 12),
('Xã Hội Thịnh', 12),
('Xã Hoàng An', 12),
('Xã Tam Dương Bắc', 12),
('Xã Vĩnh Tường', 12),
('Xã Thổ Tang', 12),
('Xã Vĩnh Hưng', 12),
('Xã Vĩnh An', 12),
('Xã Vĩnh Phú', 12),
('Xã Vĩnh Thành', 12),
('Xã Yên Lạc', 12),
('Xã Tề Lỗ', 12),
('Xã Liên Châu', 12),
('Xã Tam Hồng', 12),
('Xã Nguyệt Đức', 12),
('Xã Bình Nguyên', 12),
('Xã Xuân Lãng', 12),
('Xã Bình Xuyên', 12),
('Xã Bình Tuyền', 12),
('Phường Vĩnh Phúc', 12),
('Phường Vĩnh Yên', 12),
('Phường Phúc Yên', 12),
('Phường Xuân Hòa', 12),
('Xã Cao Phong', 12),
('Xã Mường Thàng', 12),
('Xã Thung Nai', 12),
('Xã Đà Bắc', 12),
('Xã Cao Sơn', 12),
('Xã Đức Nhàn', 12),
('Xã Quy Đức', 12),
('Xã Tân Pheo', 12),
('Xã Tiền Phong', 12),
('Xã Kim Bôi', 12),
('Xã Mường Động', 12),
('Xã Dũng Tiến', 12),
('Xã Hợp Kim', 12),
('Xã Nật Sơn', 12),
('Xã Lạc Sơn', 12),
('Xã Mường Vang', 12),
('Xã Đại Đồng', 12),
('Xã Ngọc Sơn', 12),
('Xã Nhân Nghĩa', 12),
('Xã Quyết Thắng', 12),
('Xã Thượng Cốc', 12),
('Xã Yên Phú', 12),
('Xã Lạc Thủy', 12),
('Xã An Bình', 12),
('Xã An Nghĩa', 12),
('Xã Lương Sơn', 12),
('Xã Cao Dương', 12),
('Xã Liên Sơn', 12),
('Xã Mai Châu', 12),
('Xã Bao La', 12),
('Xã Mai Hạ', 12),
('Xã Pà Cò', 12),
('Xã Tân Mai', 12),
('Xã Tân Lạc', 12),
('Xã Mường Bi', 12),
('Xã Mường Hoa', 12),
('Xã Toàn Thắng', 12),
('Xã Vân Sơn', 12),
('Xã Yên Thủy', 12),
('Xã Lạc Lương', 12),
('Xã Yên Trị', 12),
('Xã Thịnh Minh', 12),
('Phường Hòa Bình', 12),
('Phường Kỳ Sơn', 12),
('Phường Tân Hòa', 12),
('Phường Thống Nhất', 12),
('Xã Mường Phăng', 13),
('Phường Điện Biên Phủ', 13),
('Phường Mường Thanh', 13),
('Phường Mường Lay', 13),
('Xã Thanh Nưa', 13),
('Xã Thanh An', 13),
('Xã Thanh Yên', 13),
('Xã Sam Mứn', 13),
('Xã Núa Ngam', 13),
('Xã Mường Nhà', 13),
('Xã Tuần Giáo', 13),
('Xã Quài Tở', 13),
('Xã Mường Mùn', 13),
('Xã Pú Nhung', 13),
('Xã Chiềng Sinh', 13),
('Xã Tủa Chùa', 13),
('Xã Sín Chải', 13),
('Xã Sính Phình', 13),
('Xã Tủa Thàng', 13),
('Xã Sáng Nhè', 13),
('Xã Na Sang', 13),
('Xã Mường Tùng', 13),
('Xã Pa Ham', 13),
('Xã Nậm Nèn', 13),
('Xã Mường Pồn', 13),
('Xã Tìa Dình', 13),
('Xã Phình Giàng', 13),
('Xã Mường Chà', 13),
('Xã Nà Hỳ', 13),
('Xã Nà Bủng', 13),
('Xã Chà Tở', 13),
('Xã Si Pa Phìn', 13),
('Xã Mường Nhé', 13),
('Xã Sín Thầu', 13),
('Xã Mường Toong', 13),
('Xã Nậm Kè', 13),
('Xã Quảng Lâm', 13),
('Xã Mường Ảng', 13),
('Xã Nà Tấu', 13),
('Xã Búng Lao', 13),
('Xã Mường Lạn', 13),
('Xã Mường Kim', 14),
('Xã Khoen On', 14),
('Xã Than Uyên', 14),
('Xã Mường Than', 14),
('Xã Pắc Ta', 14),
('Xã Nậm Sỏ', 14),
('Xã Tân Uyên', 14),
('Xã Mường Khoa', 14),
('Xã Bản Bo', 14),
('Xã Bình Lư', 14),
('Xã Tả Lèng', 14),
('Xã Khun Há', 14),
('Phường Tân Phong', 14),
('Phường Đoàn Kết', 14),
('Xã Sin Suối Hồ', 14),
('Xã Phong Thổ', 14),
('Xã Sì Lở Lầu', 14),
('Xã Dào San', 14),
('Xã Khổng Lào', 14),
('Xã Tủa Sín Chải', 14),
('Xã Sìn Hồ', 14),
('Xã Hồng Thu', 14),
('Xã Nậm Tăm', 14),
('Xã Pu Sam Cáp', 14),
('Xã Nậm Cuổi', 14),
('Xã Nậm Mạ', 14),
('Xã Lê Lợi', 14),
('Xã Nậm Hàng', 14),
('Xã Mường Mô', 14),
('Xã Hua Bum', 14),
('Xã Pa Tần', 14),
('Xã Bum Nưa', 14),
('Xã Bum Tở', 14),
('Xã Mường Tè', 14),
('Xã Thu Lũm', 14),
('Xã Pa Ủ', 14),
('Xã Tà Tổng', 14),
('Xã Mù Cả', 14),
('Phường Tô Hiệu', 15),
('Phường Chiềng An', 15),
('Phường Chiềng Cơi', 15),
('Phường Chiềng Sinh', 15),
('Phường Mộc Châu', 15),
('Phường Mộc Sơn', 15),
('Phường Vân Sơn', 15),
('Phường Thảo Nguyên', 15),
('Xã Đoàn Kết', 15),
('Xã Lóng Sập', 15),
('Xã Chiềng Sơn', 15),
('Xã Vân Hồ', 15),
('Xã Song Khủa', 15),
('Xã Tô Múa', 15),
('Xã Xuân Nha', 15),
('Xã Quỳnh Nhai', 15),
('Xã Mường Chiên', 15),
('Xã Mường Giôn', 15),
('Xã Mường Sại', 15),
('Xã Thuận Châu', 15),
('Xã Chiềng La', 15),
('Xã Nậm Lầu', 15),
('Xã Muổi Nọi', 15),
('Xã Mường Khiêng', 15),
('Xã Co Mạ', 15),
('Xã Bình Thuận', 15),
('Xã Mường É', 15),
('Xã Long Hẹ', 15),
('Xã Mường La', 15),
('Xã Chiềng Lao', 15),
('Xã Mường Bú', 15),
('Xã Chiềng Hoa', 15),
('Xã Bắc Yên', 15),
('Xã Tà Xùa', 15),
('Xã Tạ Khoa', 15),
('Xã Xím Vàng', 15),
('Xã Pắc Ngà', 15),
('Xã Chiềng Sại', 15),
('Xã Phù Yên', 15),
('Xã Gia Phù', 15),
('Xã Tường Hạ', 15),
('Xã Mường Cơi', 15),
('Xã Mường Bang', 15),
('Xã Tân Phong', 15),
('Xã Kim Bon', 15),
('Xã Yên Châu', 15),
('Xã Chiềng Hặc', 15),
('Xã Lóng Phiêng', 15),
('Xã Yên Sơn', 15),
('Xã Chiềng Mai', 15),
('Xã Mai Sơn', 15),
('Xã Phiêng Pằn', 15),
('Xã Chiềng Mung', 15),
('Xã Phiêng Cằm', 15),
('Xã Mường Chanh', 15),
('Xã Tà Hộc', 15),
('Xã Chiềng Sung', 15),
('Xã Bó Sinh', 15),
('Xã Chiềng Khương', 15),
('Xã Mường Hung', 15),
('Xã Chiềng Khoong', 15),
('Xã Mường Lầm', 15),
('Xã Nậm Ty', 15),
('Xã Sông Mã', 15),
('Xã Huổi Một', 15),
('Xã Chiềng Sơ', 15),
('Xã Sốp Cộp', 15),
('Xã Púng Bánh', 15),
('Xã Tân Yên', 15),
('Xã Mường Bám', 15),
('Xã Ngọc Chiến', 15),
('Xã Suối Tọ', 15),
('Xã Phiêng Khoài', 15),
('Xã Mường Lạn', 15),
('Xã Mường Lèo', 15),
('Phường Hạc Thành', 16),
('Phường Quảng Phú', 16),
('Phường Đông Quang', 16),
('Phường Đông Sơn', 16),
('Phường Đông Tiến', 16),
('Phường Hàm Rồng', 16),
('Phường Nguyệt Viên', 16),
('Phường Sầm Sơn', 16),
('Phường Nam Sầm Sơn', 16),
('Phường Bỉm Sơn', 16),
('Phường Quang Trung', 16),
('Phường Ngọc Sơn', 16),
('Phường Tân Dân', 16),
('Phường Hải Lĩnh', 16),
('Phường Tĩnh Gia', 16),
('Phường Đào Duy Tư', 16),
('Phường Hải Bình', 16),
('Phường Trúc Lâm', 16),
('Phường Nghi Sơn', 16),
('Xã Các Sơn', 16),
('Xã Trường Lâm', 16),
('Xã Hà Trung', 16),
('Xã Tống Sơn', 16),
('Xã Hà Long', 16),
('Xã Hoạt Giang', 16),
('Xã Lĩnh Toại', 16),
('Xã Triệu Lộc', 16),
('Xã Đông Thành', 16),
('Xã Hậu Lộc', 16),
('Xã Hoa Lộc', 16),
('Xã Vạn Lộc', 16),
('Xã Nga Sơn', 16),
('Xã Nga Thắng', 16),
('Xã Hồ Vương', 16),
('Xã Tân Tiến', 16),
('Xã Nga An', 16),
('Xã Ba Đình', 16),
('Xã Hoằng Hóa', 16),
('Xã Hoằng Phú', 16),
('Xã Hoằng Giang', 16),
('Xã Lưu Vệ', 16),
('Xã Quảng Yên', 16),
('Xã Quảng Ngọc', 16),
('Xã Thắng Lợi', 16),
('Xã Trung Chính', 16),
('Xã Trường Văn', 16),
('Xã Thăng Bình', 16),
('Xã Tượng Lĩnh', 16),
('Xã Công Chính', 16),
('Xã Thiệu Hóa', 16),
('Xã Thiệu Quang', 16),
('Xã Thiệu Tiến', 16),
('Xã Thiệu Toán', 16),
('Xã Thiệu Trung', 16),
('Xã Yên Định', 16),
('Xã Yên Trường', 16),
('Xã Yên Phú', 16),
('Xã Quý Lộc', 16),
('Xã Yên Ninh', 16),
('Xã Định Tân', 16),
('Xã Định Hòa', 16),
('Xã Thọ Xuân', 16),
('Xã Thọ Long', 16),
('Xã Xuân Hòa', 16),
('Xã Sao Vàng', 16),
('Xã Lam Sơn', 16),
('Xã Thọ Lập', 16),
('Xã Xuân Tín', 16),
('Xã Xuân Lập', 16),
('Xã Vĩnh Lộc', 16),
('Xã Tây Đô', 16),
('Xã Biện Thượng', 16),
('Xã Triệu Sơn', 16),
('Xã Thọ Bình', 16),
('Xã Thọ Ngọc', 16),
('Xã Thọ Phú', 16),
('Xã Hợp Tiến', 16),
('Xã An Nông', 16),
('Xã Tân Ninh', 16),
('Xã Đồng Tiến', 16),
('Xã Mường Chanh', 16),
('Xã Quang Chiểu', 16),
('Xã Tam chung', 16),
('Xã Mường Lát', 16),
('Xã Pù Nhi', 16),
('Xã Nhi Sơn', 16),
('Xã Mường Lý', 16),
('Xã Trung Lý', 16),
('Xã Hồi Xuân', 16),
('Xã Nam Xuân', 16),
('Xã Thiên Phủ', 16),
('Xã Hiền Kiệt', 16),
('Xã Phú Xuân', 16),
('Xã Phú Lệ', 16),
('Xã Trung Thành', 16),
('Xã Trung Sơn', 16),
('Xã Na Mèo', 16),
('Xã Sơn Thủy', 16),
('Xã Sơn Điện', 16),
('Xã Mường Mìn', 16),
('Xã Tam Thanh', 16),
('Xã Tam Lư', 16),
('Xã Quan Sơn', 16),
('Xã Trung Hạ', 16),
('Xã Linh Sơn', 16),
('Xã Đồng Lương', 16),
('Xã Văn Phú', 16),
('Xã Giao An', 16),
('Xã Yên Khương', 16),
('Xã Yên Thắng', 16),
('Xã Văn Nho', 16),
('Xã Thiết Ống', 16),
('Xã Bá Thước', 16),
('Xã Cổ Lũng', 16),
('Xã Pù Luông', 16),
('Xã Điền Lư', 16),
('Xã Điền Quang', 16),
('Xã Quý Lương', 16),
('Xã Ngọc Lặc', 16),
('Xã Thạch Lập', 16),
('Xã Cẩm Thạch', 16),
('Xã Cẩm Thủy', 16),
('Xã Cẩm Tú', 16),
('Xã Cẩm Vân', 16),
('Xã Cẩm Tân', 16),
('Xã Kim Tân', 16),
('Xã Vân Du', 16),
('Xã Ngọc Trạo', 16),
('Xã Thạch Bình', 16),
('Xã Thành Vinh', 16),
('Xã Thạch Quảng', 16),
('Xã Như Xuân', 16),
('Xã Thượng Ninh', 16),
('Xã Xuân Bình', 16),
('Xã Hóa Quỳ', 16),
('Xã Thanh Quân', 16),
('Xã Thanh Phong', 16),
('Xã Xuân Du', 16),
('Xã Mậu Lâm', 16),
('Xã Như Thanh', 16),
('Xã Yên Thọ', 16),
('Xã Xuân Thái', 16),
('Xã Thanh Kỳ', 16),
('Xã Bát Mọt', 16),
('Xã Yên Nhân', 16),
('Xã Lương Sơn', 16),
('Xã Thường Xuân', 16),
('Xã Luận Thành', 16),
('Xã Tân Thành', 16),
('Xã Vạn Xuân', 16),
('Xã Thắng Lộc', 16),
('Xã Xuân Chinh', 16),
('Xã Anh Sơn', 17),
('Xã Yên Xuân', 17),
('Xã Nhân Hòa', 17),
('Xã Anh Sơn Đông', 17),
('Xã Vĩnh Tường', 17),
('Xã Thành Bình Thọ', 17),
('Xã Con Cuông', 17),
('Xã Môn Sơn', 17),
('Xã Mậu Thạch', 17),
('Xã Cam Phục', 17),
('Xã Châu Khê', 17),
('Xã Bình Chuẩn', 17),
('Xã Diễn Châu', 17),
('Xã Đức Châu', 17),
('Xã Quảng Châu', 17),
('Xã Hải Châu', 17),
('Xã Tân Châu', 17),
('Xã An Châu', 17),
('Xã Minh Châu', 17),
('Xã Hùng Châu', 17),
('Xã Đô Lương', 17),
('Xã Bạch Ngọc', 17),
('Xã Văn Hiến', 17),
('Xã Bạch Hà', 17),
('Xã Thuần Trung', 17),
('Xã Lương Sơn', 17),
('Phường Hoàng Mai', 17),
('Phường Tân Mai', 17),
('Phường Quỳnh Mai', 17),
('Xã Hưng Nguyên', 17),
('Xã Yên Trung', 17),
('Xã Hưng Nguyên Nam', 17),
('Xã Lam Thành', 17),
('Xã Mường Xén', 17),
('Xã Hữu Kiệm', 17),
('Xã Nậm Cắn', 17),
('Xã Chiêu Lưu', 17),
('Xã Na Loi', 17),
('Xã Mường Típ', 17),
('Xã Huồi Tụ', 17),
('Xã Mường Lống', 17),
('Xã Vạn An', 17),
('Xã Nam Đàn', 17),
('Xã Đại Huệ', 17),
('Xã Nghĩa Mai', 17),
('Xã Nghĩa Hưng', 17),
('Xã Nghĩa Khánh', 17),
('Xã Nghĩa Lộc', 17),
('Xã Nghi Lộc', 17),
('Xã Phúc Lộc', 17),
('Xã Đông Lộc', 17),
('Xã Trung Lộc', 17),
('Xã Thần Lĩnh', 17),
('Xã Hải Lộc', 17),
('Xã Văn Kiều', 17),
('Xã Quế Phong', 17),
('Xã Tiền Phong', 17),
('Xã Tri Lễ', 17),
('Xã Mường Quàng', 17),
('Xã Thông Thụ', 17),
('Xã Quỳ Châu', 17),
('Xã Châu Tiến', 17),
('Xã Hùng Chân', 17),
('Xã Châu Bình', 17),
('Xã Quỳ Hợp', 17),
('Xã Tam Hợp', 17),
('Xã Châu Lộc', 17),
('Xã Châu Hồng', 17),
('Xã Mường Ham', 17),
('Xã Mường Chọng', 17),
('Xã Minh Hợp', 17),
('Xã Quỳnh Lưu', 17),
('Xã Quỳnh Văn', 17),
('Xã Quỳnh Anh', 17),
('Xã Quỳnh Tam', 17),
('Xã Quỳnh Phú', 17),
('Xã Quỳnh Sơn', 17),
('Xã Quỳnh Thắng', 17),
('Xã Tân Kỳ', 17),
('Xã Tân Phú', 17),
('Xã Tân An', 17),
('Xã Nghĩa Đồng', 17),
('Xã Giai Xuân', 17),
('Xã Nghĩa Hành', 17),
('Xã Tiên Đồng', 17),
('Phường Thái Hòa', 17),
('Phường Tây Hiếu', 17),
('Xã Đông Hiếu', 17),
('Xã Cát Ngạn', 17),
('Xã Tam Đồng', 17),
('Xã Hạnh Lâm', 17),
('Xã Sơn Lâm', 17),
('Xã Hoa Quân', 17),
('Xã Kim Bảng', 17),
('Xã Bích Hào', 17),
('Xã Đại Đồng', 17),
('Xã Xuân Lâm', 17),
('Xã Tam Quang', 17),
('Xã Tam Thái', 17),
('Xã Tương Dương', 17),
('Xã Lượng Minh', 17),
('Xã Yên Na', 17),
('Xã Yên Hòa', 17),
('Xã Nga My', 17),
('Xã Hữu Khuông', 17),
('Xã Nhôn Mai', 17),
('Phường Trường Vinh', 17),
('Phường Thành Vinh', 17),
('Phường Vinh Hưng', 17),
('Phường Vinh Phú', 17),
('Phường Vinh Lộc', 17),
('Phường Cửa Lò', 17),
('Xã Yên Thành', 17),
('Xã Quan Thành', 17),
('Xã Hợp Minh', 17),
('Xã Vân Tụ', 17),
('Xã Vân Du', 17),
('Xã Quang Đồng', 17),
('Xã Giai Lạc', 17),
('Xã Bình Minh', 17),
('Xã Đông Thành', 17),
('Phường Sông Trí', 18),
('Phường Hải Ninh', 18),
('Phường Hoành Sơn', 18),
('Phường Vũng Áng', 18),
('Xã Kỳ Xuân', 18),
('Xã Kỳ Anh', 18),
('Xã Kỳ Hoa', 18),
('Xã Kỳ Văn', 18),
('Xã Kỳ Khang', 18),
('Xã Kỳ Lạc', 18),
('Xã Kỳ Thượng', 18),
('Xã Cẩm Xuyên', 18),
('Xã Thiên Cầm', 18),
('Xã Cẩm Duệ', 18),
('Xã Cẩm Hưng', 18),
('Xã Cẩm Lạc', 18),
('Xã Cẩm Trung', 18),
('Xã Yên Hòa', 18),
('Phường Thành Sen', 18),
('Phường Trần Phú', 18),
('Phường Hà Huy Tập', 18),
('Xã Thạch Lạc', 18),
('Xã Đồng Tiến', 18),
('Xã Thạch Khê', 18),
('Xã Cẩm Bình', 18),
('Xã Thạch Hà', 18),
('Xã Toàn Lưu', 18),
('Xã Việt Xuyên', 18),
('Xã Đông Kinh', 18),
('Xã Thạch Xuân', 18),
('Xã Lộc Hà', 18),
('Xã Hồng Lộc', 18),
('Xã Mai Phụ', 18),
('Xã Can Lộc', 18),
('Xã Tùng Lộc', 18),
('Xã Gia Hanh', 18),
('Xã Trường Lưu', 18),
('Xã Xuân Lộc', 18),
('Xã Đồng Lộc', 18),
('Phường Bắc Hồng Lĩnh', 18),
('Phường Nam Hồng Lĩnh', 18),
('Xã Tiên Điền', 18),
('Xã Nghi Xuân', 18),
('Xã Cổ Đạm', 18),
('Xã Đan Hải', 18),
('Xã Đức Thọ', 18),
('Xã Đức Quang', 18),
('Xã Đức Đồng', 18),
('Xã Đức Thịnh', 18),
('Xã Đức Minh', 18),
('Xã Hương Khê', 18),
('Xã Hương Phố', 18),
('Xã Hương Đô', 18),
('Xã Hà Linh', 18),
('Xã Hương Bình', 18),
('Xã Phúc Trạch', 18),
('Xã Hương Xuân', 18),
('Xã Sơn Kim 1', 18),
('Phường Đồng Hới', 19),
('Phường Đồng Thuận', 19),
('Phường Đồng Sơn', 19),
('Xã Nam Gianh', 19),
('Xã Nam Ba Đồn', 19),
('Phường Ba Đồn', 19),
('Phường Bắc Gianh', 19),
('Xã Tuyên Lâm', 19),
('Xã Tuyên Sơn', 19),
('Xã Đồng Lê', 19),
('Xã Tuyên Phú', 19),
('Xã Tuyên Bình', 19),
('Xã Tuyên Hóa', 19),
('Xã Tân Gianh', 19),
('Xã Trung Thuần', 19),
('Xã Quảng Trạch', 19),
('Xã Hòa Trạch', 19),
('Xã Phú Trạch', 19),
('Xã Thượng Trạch', 19),
('Xã Phong Nha', 19),
('Xã Bắc Trạch', 19),
('Xã Đông Trạch', 19),
('Xã Hoàn Lão', 19),
('Xã Bố Trạch', 19),
('Xã Nam Trạch', 19),
('Xã Quảng Ninh', 19),
('Xã Ninh Châu', 19),
('Xã Trường Ninh', 19),
('Xã Trường Sơn', 19),
('Xã Lệ Thủy', 19),
('Xã Cam Hồng', 19),
('Xã Sen Ngư', 19),
('Xã Tân Mỹ', 19),
('Xã Trường Phú', 19),
('Xã Lệ Ninh', 19),
('Xã Kim Ngân', 19),
('Phường Đông Hà', 19),
('Phường Nam Đông Hà.', 19),
('Phường Quảng Trị', 19),
('Xã Vĩnh Linh', 19),
('Xã Cửa Tùng', 19),
('Xã Vĩnh Hoàng', 19),
('Xã Vĩnh Thủy', 19),
('Xã Bến Quan', 19),
('Xã Cồn Tiên', 19),
('Xã Cửa Việt', 19),
('Xã Gio Linh', 19),
('Xã Bến Hải', 19),
('Xã Hướng Lập', 19),
('Xã Hướng Phùng', 19),
('Xã Khe Sanh', 19),
('Xã Tân Lập', 19),
('Xã Lao Bảo', 19),
('Xã Lìa', 19),
('Xã A Dơi', 19),
('Xã La Lay', 19),
('Xã Tà Rụt', 19),
('Xã Đakrông', 19),
('Xã Ba Lòng', 19),
('Xã Hướng Hiệp', 19),
('Xã Cam Lộ', 19),
('Xã Hiếu Giang', 19),
('Xã Triệu Phong', 19),
('Xã Ái Tử', 19),
('Xã Triệu Bình', 19),
('Xã Triệu Cơ', 19),
('Xã Nam Cửa Việt', 19),
('Xã Diên Sanh', 19),
('Xã Mỹ Thủy', 19),
('Xã Hải Lăng', 19),
('Xã Vĩnh Định', 19),
('Xã Nam Hải Lăng', 19),
('Đặc khu Cồn Cỏ', 19),
('Phường Thuận An', 20),
('Phường Hóa Châu', 20),
('Phường Mỹ Thượng', 20),
('Phường Vỹ Dạ', 20),
('Phường Thuận Hóa', 20),
('Phường An Cựu', 20),
('Phường Thủy Xuân', 20),
('Phường Kim Long', 20),
('Phường Hương An', 20),
('Phường Phú Xuân', 20),
('Phường Hương Trà', 20),
('Phường Kim Trà', 20),
('Phường Thanh Thủy', 20),
('Phường Hương Thủy', 20),
('Phường Phú Bài', 20),
('Phường Phong Điền', 20),
('Phường Phong Thái', 20),
('Phường Phong Dinh', 20),
('Phường Phong Phú', 20),
('Phường Phong Quảng', 20),
('Xã Đan Điền', 20),
('Xã Quảng Điền', 20),
('Xã Phú Vinh', 20),
('Xã Phú Hồ', 20),
('Xã Phú Vang', 20),
('Xã Vinh Lộc', 20),
('Xã Hưng Lộc', 20),
('Xã Lộc An', 20),
('Xã Phú Lộc', 20),
('Xã Chân Mây – Lăng Cô', 20),
('Xã Long Quảng', 20),
('Xã Nam Đông', 20),
('Xã Khe Tre', 20),
('Xã Bình Điền', 20),
('Xã A Lưới 1', 20),
('Xã A Lưới 2', 20),
('Xã A Lưới 3', 20),
('Xã A Lưới 4', 20),
('Xã A Lưới 5', 20),
('Phường Dương Nỗ', 20),
('Phường Hải Châu', 21),
('Phường Hòa Cường', 21),
('Phường Thanh Khê', 21),
('Phường An Khê', 21),
('Phường An Hải', 21),
('Phường Sơn Trà', 21),
('Phường Ngũ Hành Sơn', 21),
('Phường Hòa Khánh', 21),
('Phường Hải Vân', 21),
('Phường Liên Chiểu', 21),
('Phường Cẩm Lệ', 21),
('Phường Hòa Xuân', 21),
('Xã Hòa Vang', 21),
('Xã Hòa Tiến', 21),
('Xã Bà Nà', 21),
('Đặc khu Hoàng Sa', 21),
('Xã Núi Thành', 21),
('Xã Tam Mỹ', 21),
('Xã Tam Anh', 21),
('Xã Đức Phú', 21),
('Xã Tam Xuân', 21),
('Xã Tam Hải', 21),
('Phường Tam Kỳ', 21),
('Phường Quảng Phú', 21),
('Phường Hương Trà', 21),
('Phường Bàn Thạch', 21),
('Xã Tây Hồ', 21),
('Xã Chiên Đàn', 21),
('Xã Phú Ninh', 21),
('Xã Lãnh Ngọc', 21),
('Xã Tiên Phước', 21),
('Xã Thạnh Bình', 21),
('Xã Sơn Cẩm Hà', 21),
('Xã Trà Liên', 21),
('Xã Trà Giáp', 21),
('Xã Trà Tân', 21),
('Xã Trà Đốc', 21),
('Xã Trà My', 21),
('Xã Trà Mai', 21),
('Xã Trà Tập', 21),
('Xã Trà Vân', 21),
('Xã Trà Linh', 21),
('Xã Trà Leng', 21),
('Xã Thăng Bình', 21),
('Xã Thăng An', 21),
('Xã Thăng Trường', 21),
('Xã Thăng Điền', 21),
('Xã Thăng Phú', 21),
('Xã Đồng Dương', 21),
('Xã Quế Sơn Trung', 21),
('Xã Quế Sơn', 21),
('Xã Xuân Phú', 21),
('Xã Nông Sơn', 21),
('Xã Quế Phước', 21),
('Xã Duy Nghĩa', 21),
('Xã Nam Phước', 21),
('Xã Duy Xuyên', 21),
('Xã Thu Bồn', 21),
('Phường Điện Bàn', 21),
('Phường Điện Bàn Đông', 21),
('Phường An Thắng', 21),
('Phường Điện Bàn Bắc', 21),
('Xã Điện Bàn Tây', 21),
('Xã Gò Nổi', 21),
('Phường Hội An', 21),
('Phường Hội An Đông', 21),
('Phường Hội An Tây', 21),
('Xã Tân Hiệp', 21),
('Xã Đại Lộc', 21),
('Xã Hà Nha', 21),
('Xã Thượng Đức', 21),
('Xã Vu Gia', 21),
('Xã Phú Thuận', 21),
('Xã Thạnh Mỹ', 21),
('Xã Bến Giằng', 21),
('Xã Nam Giang', 21),
('Xã Đắc Pring', 21),
('Xã La Dêê', 21),
('Xã La Êê', 21),
('Xã Sông Vàng', 21),
('Xã Sông Kôn', 21),
('Xã Đông Giang', 21),
('Xã Bến Hiên', 21),
('Xã Phước Trà', 21),
('Xã Khâm Đức', 21),
('Xã Phước Năng', 21),
('Xã Phước Chánh', 21),
('Xã Phước Thành', 21),
('Xã Phước Hiệp', 21),
('Xã Tịnh Khê', 22),
('Phường Trương Quang Trọng', 22),
('Xã An Phú', 22),
('Phường Cẩm Thành', 22),
('Phường Nghĩa Lộ', 22),
('Phường Trà Câu', 22),
('Xã Nguyễn Nghiêm', 22),
('Phường Đức Phổ', 22),
('Xã Khánh Cường', 22),
('Phường Sa Huỳnh', 22),
('Xã Bình Minh', 22),
('X Cày', 22),
('Xã Mộ Đức', 22),
('Xã Lân Phong', 22),
('Xã Trà Bồng', 22),
('Xã Đông Trà Bồng', 22),
('Xã Tây Trà', 22),
('Xã Thanh Bồng', 22),
('Xã Cà Đam', 22),
('Xã Tây Trà Bồng', 22),
('Xã Sơn Hạ', 22),
('Xã Sơn Linh', 22),
('Xã Sơn Hà', 22),
('Xã Sơn Thủy', 22),
('Xã Sơn Kỳ', 22),
('Xã Sơn Tây', 22),
('Xã Sơn Tây Thượng', 22),
('Xã Sơn Tây Hạ', 22),
('Xã Minh Long', 22),
('Xã Sơn Mai', 22),
('Xã Ba Vì', 22),
('Xã Ba Tô', 22),
('Xã Ba Dinh', 22),
('Xã Ba Tơ', 22),
('Xã Ba Vinh', 22),
('Xã Ba Động', 22),
('Xã Đặng Thùy Trâm', 22),
('Xã Ba Xa', 22),
('Đặc khu Lý Sơn', 22),
('Phường Kon Tum', 22),
('Phường Đăk Cấm', 22),
('Phường Đăk BLa', 22),
('Xã Ngọk Bay', 22),
('Xã Ia Chim', 22),
('Xã Đăk Rơ Wa', 22),
('Xã Đăk Pxi', 22),
('Xã Đăk Mar', 22),
('Xã Đăk Ui', 22),
('Xã Ngọk Réo', 22),
('Xã Đăk Hà', 22),
('Xã Ngọk Tụ', 22),
('Xã Đăk Tô', 22),
('Xã Kon Đào', 22),
('Xã Đăk Sao', 22),
('Xã Đăk Tờ Kan', 22),
('Xã Tu Mơ Rông', 22),
('Xã Măng Ri', 22),
('Xã Bờ Y', 22),
('Xã Sa Loong', 22),
('Xã Dục Nông', 22),
('Xã Xốp', 22),
('Xã Ngọc Linh', 22),
('Xã Đăk Plô', 22),
('Xã Đăk Pék', 22),
('Xã Đăk Môn', 22),
('Xã Sa Thầy', 22),
('Xã Sa Bình', 22),
('Xã Ya Ly', 22),
('Xã Ia Tơi', 22),
('Xã Đăk Kôi', 22),
('Xã Kon Braih', 22),
('Xã Đăk Rve', 22),
('Xã Măng Đen', 22),
('Xã Măng Bút', 22),
('Xã Kon Plông', 22),
('Xã Đăk Long', 22),
('Xã Rờ Kơi', 22),
('Xã Mô Rai', 22),
('Xã Ia Đal', 22),
('Phường Nha Trang', 23),
('Phường Bắc Nha Trang', 23),
('Phường Tây Nha Trang', 23),
('Phường Nam Nha Trang', 23),
('Phường Bắc Cam Ranh', 23),
('Phường Cam Ranh', 23),
('Phường Cam Linh', 23),
('Phường Ba Ngòi', 23),
('Xã Nam Cam Ranh', 23),
('Xã Bắc Ninh Hòa', 23),
('Phường Ninh Hòa', 23),
('Xã Tân Định', 23),
('Phường Đông Ninh Hòa', 23),
('Phường Hòa Thắng', 23),
('Xã Nam Ninh Hòa', 23),
('Xã Tây Ninh Hòa', 23),
('Xã Hòa Trí', 23),
('Xã Đại Lãnh', 23),
('Xã Tu Bông', 23),
('Xã Vạn Thắng', 23),
('Xã Vạn Ninh', 23),
('Xã Vạn Hưng', 23),
('Xã Diên Khánh', 23),
('Xã Diên Lạc', 23),
('Xã Diên Điền', 23),
('Xã Diên Lâm', 23),
('Xã Diên Thọ', 23),
('Xã Suối Hiệp', 23),
('Xã Cam Lâm', 23),
('Xã Suối Dầu', 23),
('Xã Cam Hiệp', 23),
('Xã Cam An', 23),
('Xã Bắc Khánh Vĩnh', 23),
('Xã Trung Khánh Vĩnh', 23),
('Xã Tây Khánh Vĩnh', 23),
('Xã Nam Khánh Vĩnh', 23),
('Xã Khánh Vĩnh', 23),
('Xã Khánh Sơn', 23),
('Xã Tây Khánh Sơn', 23),
('Xã Đông Khánh Sơn', 23),
('Đặc khu Trường Sa', 23),
('Phường Phan Rang', 23),
('Phường Đông Hải', 23),
('Phường Ninh Chử', 23),
('Phường Bảo An', 23),
('Phường Đô Vinh', 23),
('Xã Ninh Phước', 23),
('Xã Phước Hữu', 23),
('Xã Phước Hậu', 23),
('Xã Thuận Nam', 23),
('Xã Cà Ná', 23),
('Xã Phước Hà', 23),
('Xã Phước Dinh', 23),
('Xã Ninh Hải', 23),
('Xã Xuân Hải', 23),
('Xã Vĩnh Hải', 23),
('Xã Thuận Bắc', 23),
('Xã Công Hải', 23),
('Xã Ninh Sơn', 23),
('Xã Lâm Sơn', 23),
('Xã Anh Dũng', 23),
('Xã Mỹ Sơn', 23),
('Xã Bác Ái Đông', 23),
('Xã Bác Ái', 23),
('Xã Bác Ái Tây', 23),
('Phường Bình Định', 24),
('Phường An Nhơn', 24),
('Phường An Nhơn Đông', 24),
('Phường An Nhơn Nam', 24),
('Phường An Nhơn Bắc', 24),
('Xã An Nhơn Tây', 24),
('Phường Bồng Sơn', 24),
('Phường Hoài Nhơn', 24),
('Phường Tam Quan', 24),
('Phường Hoài Nhơn Đông', 24),
('Phường Hoài Nhơn Tây', 24),
('Phường Hoài Nhơn Nam', 24),
('Phường Hoài Nhơn Bắc', 24),
('Xã Phù Cát', 24),
('Xã Xuân An', 24),
('Xã Ngô Mây', 24),
('Xã Cát Tiến', 24),
('Xã Đề Gi', 24),
('Xã Hòa Hội', 24),
('Xã Hội Sơn', 24),
('Xã Phù Mỹ', 24),
('Xã An Lương', 24),
('Xã Bình Dương', 24),
('Xã Phù Mỹ Đông', 24),
('Xã Phù Mỹ Tây', 24),
('Xã Tuy Phước Bắc', 24),
('Xã Tây Sơn', 24),
('Xã Bình Khê', 24),
('Xã Bình Phú', 24),
('Xã Bình Hiệp', 24),
('Xã Ân Hảo', 24),
('Xã Vân Canh', 24),
('Xã Canh Vinh', 24),
('Xã Canh Liên', 24),
('Xã Vĩnh Thạnh', 24),
('Xã Vĩnh Thịnh', 24),
('Xã Vĩnh Quang', 24),
('Xã Vĩnh Sơn', 24),
('Xã An Hòa', 24),
('Xã An Lão', 24),
('Xã An Vinh', 24),
('Xã An Toàn', 24),
('Phường Pleiku', 24),
('Phường Hội Phú', 24),
('Phường Thống Nhất', 24),
('Phường Diên Hồng', 24),
('Phường An Phú', 24),
('Xã Biển Hồ', 24),
('Xã Gào', 24),
('Xã Ia Ly', 24),
('Xã Chư Păh', 24),
('Xã Ia Kh', 24),
('Xã Chư Pưh', 24),
('Xã Ia Le', 24),
('Xã Ia Hrú', 24),
('Phường An Khê', 24),
('Phường An Bình', 24),
('Xã Cửu An', 24),
('Xã Đak Pơ', 24),
('Xã Ya Hội', 24),
('Xã Kbang', 24),
('Xã Kông Bơ La', 24),
('Xã Tơ Tung', 24),
('Xã Sơn Lang', 24),
('Xã Đak Rong', 24),
('Xã Kông Chro', 24),
('Xã Ya Ma', 24),
('Xã Chư Krey', 24),
('Xã SRó', 24),
('Xã Đăk Song', 24),
('Xã Chơ Long', 24),
('Phường Ayun Pa', 24),
('Xã Ia Rbol', 24),
('Xã Ia Sao', 24),
('Xã Phú Thiện Xã Ia Rsai', 24),
('Xã Krong', 24),
('Xã Hòa Phú', 25),
('Phường Buôn Ma Thuột', 25),
('Phường Tân An', 25),
('Phường Tân Lập', 25),
('Phường Thành Nhất', 25),
('Phường Ea Kao', 25),
('Xã Ea Drông', 25),
('Phường Buôn Hồ', 25),
('Phường Cư Bao', 25),
('Xã Ea Súp', 25),
('Xã Ea Rốk', 25),
('Xã Buôn Đôn', 25),
('Xã Ea Kiết', 25),
('Xã Ea M’Droh', 25),
('Xã Quảng Phú', 25),
('Xã Cuôr Đăng', 25),
('Xã Ea Knuếc', 25),
('Xã Tân Tiến', 25),
('Xã Ea Phê', 25),
('Xã Ea Kly [4 Lắk', 25),
('Xã Ea Trang', 25),
('Xã Hòa Sơn', 25),
('Xã Dang Kang', 25),
('Xã Krông Bông', 25),
('Xã Yang Mao', 25),
('Xã Cư Pui', 25),
('Xã Liên Sơn Lắk', 25),
('Xã Đắk Liêng', 25),
('Xã Nam Ka', 25),
('Xã Đắk Phơi', 25),
('Xã Krông Nô', 25),
('Xã Ea Ning', 25),
('Xã Dray Bhăng', 25),
('Phường Phú Yên', 25),
('Phường Bình Kiến', 25),
('Xã Xuân Thọ', 25),
('Xã Xuân Cảnh', 25),
('Xã Xuân Lộc', 25),
('Phường Xuân Đài', 25),
('Phường Sông Cầu', 25),
('Xã Hòa Xuân', 25),
('Phường Đông Hòa', 25),
('Phường Hòa Hiệp', 25),
('Xã Tuy An Bắc Xã Tây Hòa', 25),
('Xã Hòa Thịnh', 25),
('Xã Hòa Mỹ', 25),
('Xã Sơn Thành', 25),
('Xã Sơn Hòa', 25),
('Xã Vân Hòa', 25),
('Xã Tây Sơn', 25),
('Xã Suối Trai', 25),
('Xã Ea Ly', 25),
('Xã Ea Bá', 25),
('Xã Đức Bình', 25),
('Xã Sông Hinh', 25),
('Xã Xuân Lãnh', 25),
('Xã Phú Mỡ', 25),
('Xã Xuân Phước', 25),
('Xã Đồng Xuân', 25),
('Phường Xuân Hương - Đà Lạt', 26),
('Phường Cam Ly - Đà Lạt', 26),
('Phường Lâm Viên - Đà Lạt', 26),
('Phường Xuân Trường - Đà Lạt', 26),
('Phường Langbiang - Đà Lạt', 26),
('Phường 1 Bảo Lộc', 26),
('Phường 2 Bảo Lộc', 26),
('Phường 3 Bảo Lộc', 26),
('Phường B Lao', 26),
('Xã Lạc Dương', 26),
('Xã Đơn Dương', 26),
('Xã Ka Đô', 26),
('Xã Quảng Lập', 26),
('Xã DRan', 26),
('Xã Nam Hà - Lâm Hà', 26),
('Xã Nam Ban - Lâm Hà', 26),
('Xã Tân Hà - Lâm Hà', 26),
('Xã Phúc Thọ - Lâm Hà', 26),
('Xã Đam Rông 1', 26),
('Xã Đam Rông 2', 26),
('Xã Đam Rông 3', 26),
('Xã Đam Rông 4', 26),
('Xã Di Linh', 26),
('Xã Hòa Ninh', 26),
('Xã Hòa Bắc', 26),
('Xã Đinh Trang Thượng', 26),
('Xã Bảo Thuận', 26),
('Xã Sơn Điền', 26),
('Xã Đạ Huoai 2', 26),
('Xã Đạ Huoai 3', 26),
('Xã Đạ Tẻh', 26),
('Xã Đạ Tẻh 2', 26),
('Xã Đạ Tẻh 3', 26),
('Xã Cát Tiên', 26),
('Xã Cát Tiên 2', 26),
('Xã Cát Tiên 3', 26),
('Phường Hàm Thắng', 26),
('Phường Bình Thuận', 26),
('Phường Mũi Né', 26),
('Phường Phú Thuỷ', 26),
('Phường Phan Thiết', 26),
('Phường Tiến Thành', 26),
('Phường La Gi', 26),
('Phường Phước Hội', 26),
('Xã Tuyên Quang', 26),
('Xã Tân Hải', 26),
('Xã Vĩnh Hảo', 26),
('Xã Liên Hương', 26),
('Xã Tuy Phong', 26),
('Xã Phan Rí Cửa', 26),
('Xã Bắc Bình', 26),
('Xã Hồng Thái', 26),
('Xã Hải Ninh', 26),
('Xã Phan Sơn', 26),
('Xã Sông Lũy', 26),
('Xã Lương Sơn', 26),
('Xã Hòa Thắng Đồng', 26),
('Xã Tân Thành', 26),
('Xã Hàm Thuận Nam', 26),
('Xã Tân Lập', 26),
('Xã Tân Minh', 26),
('Xã Hàm Tân', 26),
('Xã Sơn Mỹ', 26),
('Xã Bắc Ruộng', 26),
('Xã Nghị Đức', 26),
('Xã Đồng Kho', 26),
('Xã Tánh Linh', 26),
('Xã Suối Kiết', 26),
('Xã Nam Thành', 26),
('Xã Đức Linh', 26),
('Xã Hoài Đức', 26),
('Xã Trà Tân', 26),
('Đặc khu Phú Quý', 26),
('Phường Bắc Gia Nghĩa', 26),
('Phường Nam Gia Nghĩa', 26),
('Phường Đông Gia Nghĩa', 26),
('Xã Đắk Wil', 26),
('Xã Nam Dong', 26),
('Xã Cư Jút', 26),
('Xã Lâm Đồng', 26),
('Xã Đắk song', 26),
('Xã Đức An', 26),
('Xã Thuận Hạnh', 26),
('Xã Trường Xuân', 26),
('Xã Tà Đùng', 26),
('Xã Quảng Khê', 26),
('Xã Quảng Tân', 26),
('Xã Tuy Đức', 26),
('Xã Kiến Đức', 26),
('Xã Nhân Cơ', 26),
('Xã Quảng Tín', 26),
('Xã Ninh Gia', 26),
('Xã Quảng Hòa', 26),
('Xã Quảng Sơn', 26),
('Xã Quảng Trực72', 26),
('Phường Kiến Tường', 27),
('Xã Bình Hoà', 27),
('Xã Mộc Hoá', 27),
('Xã Hậu Thạnh', 27),
('Xã Nhơn Hòa Lập', 27),
('Xã Nhơn Ninh', 27),
('Xã Tân Thạnh', 27),
('Xã Bình Thành', 27),
('Xã Thạnh Phước', 27),
('Xã Thạnh Hóa', 27),
('Xã Tân Tây', 27),
('Xã Thủ Thừa', 27),
('Xã Mỹ An', 27),
('Xã Mỹ Thạnh', 27),
('Xã Tân Long', 27),
('Xã Mỹ Quý', 27),
('Xã Đông Thành', 27),
('Xã Đức Lập', 27),
('Xã Mỹ Hạnh', 27),
('Xã Đức Hòa', 27),
('Xã Thạnh Lợi', 27),
('Xã Bình Đức', 27),
('Xã Mỹ Lệ', 27),
('Xã Tân Lân', 27),
('Xã Cần Đước', 27),
('Xã Long Hựu', 27),
('Xã Phước Lý', 27),
('Xã Mỹ Lộc', 27),
('Xã Cần Giuộc', 27),
('Xã Phước Vĩnh Tây Tỉnh', 27),
('Xã Vĩnh Công', 27),
('Phường Long An', 27),
('Phường Tân An', 27),
('Phường Hoà Thành', 27),
('Phường Thanh Điền', 27),
('Phường Trảng Bàng', 27),
('Phường An Tịnh', 27),
('Phường Gò Dầu', 27),
('Phường Gia Lộc', 27),
('Xã Hưng Thuận', 27),
('Xã Phước Chỉ', 27),
('Xã Thạnh Đức', 27),
('Xã Phước Thạnh', 27),
('Xã Tân Lập', 27),
('Xã Tân Biên [483ữ', 27),
('Xã Long Thuận', 27),
('Xã Bến Cầu', 27),
('Phường Biên Hòa', 28),
('Phường Tr87', 28),
('Xã Phước An', 28),
('Xã Phước Thái', 28),
('Xã Long Phước', 28),
('Xã Bình An', 28),
('Xã Long Thành', 28),
('Xã An Phước', 28),
('Xã Dầu Giây', 28),
('Xã Gia Kiệm', 28),
('Xã Thống Nhất', 28),
('Phường Bình Lộc', 28),
('Phường Bảo Vinh', 28),
('Phường Xuân Lập', 28),
('Phường Long Khánh', 28),
('Phường Hàng Gòn', 28),
('Xã Xuân Quế', 28),
('Xã Xuân Thành', 28),
('Xã Xuân Bắc', 28),
('Xã La Ngà', 28),
('Xã Định Quán', 28),
('Xã Phú Vinh', 28),
('Xã Phú Hòa', 28),
('Xã Tà Lài', 28),
('Xã Nam Cát Phường Bình Long', 28),
('Phường An Lộc', 28),
('Xã Lộc Thành', 28),
('Xã Lộc Ninh', 28),
('Xã Lộc Hưng', 28),
('Xã Lộc Tấn', 28),
('Xã Lộc Thạnh', 28),
('Xã Lộc Quang', 28),
('Xã Tân Tiến', 28),
('Xã Thiện Hưng', 28),
('Xã Hưng Phước', 28),
('Xã Phú Nghĩa', 28),
('Xã Đa Kia', 28),
('Phường Phước Bình', 28),
('Phường Phước Long Tỉnh Đồng Nai Nai', 28),
('Xã Tân Lợi', 28),
('Xã Đồng Phú', 28),
('Xã Phước Sơn', 28),
('Xã Nghĩa Trung', 28),
('Xã Bù Đăng', 28),
('Xã Thọ Sơn', 28),
('Xã Đak Nhau', 28),
('Đồng Nai', 28),
('Phường Vũng Tàu', 29),
('Phường Tam Thắng', 29),
('Phường Rạch Dừa *6', 29),
('Xã Châu Pha', 29),
('Xã Ngãi Giao', 29),
('Xã Hồ Tràm', 29),
('Xã Xuyên Mộc', 29),
('Xã Hòa Hội', 29),
('Xã Bàu Lâm', 29),
('Xã Phước Hải', 29),
('Xã Long Hải09', 29),
('Phường Thuận Giao', 29),
('Phường Bình Hòa', 29),
('Phường Lái Thiêu', 29),
('Phường An Phú', 29),
('Phường Bình Dương', 29),
('Phường Chánh Hiệp', 29),
('Phường Thủ Dầu Một', 29),
('Phường Phú Lợi', 29),
('Phường Vĩnh Tân', 29),
('Phường Bình Cơ', 29),
('Phường Tân Uyên', 29),
('Phường Tân Hiệp', 29),
('Phường Tân Khánh', 29),
('Phường Hòa Lợi', 29),
('Phường Phú An', 29),
('4', 29),
('Xã Phước Hòa', 29),
('Xã Phú Giáo', 29),
('Xã Trừ Văn Thố', 29),
('Xã Bàu Bàng', 29),
('Xã Minh Thạnh', 29),
('Xã Long Hòa', 29),
('Xã Dầu Tiếng', 29),
('Xã Thanh An517', 29),
('Phường Xóm Chiếu', 29),
('Phường Khánh Hội', 29),
('Phường Vĩnh Hội', 29),
('Phường Chợ Quán', 29),
('Phường An Đông', 29),
('Phường Chợ Lớn', 29),
('Phường Bình Tây', 29),
('Ph', 29),
('Phường Phú Định', 29),
('Phường Bình Đông', 29),
('Phường Diên Hồng', 29),
('Phường Vườn Lài', 29),
('Phường Hòa Hưng', 29),
('Phường Minh Phụng', 29),
('Phường Bình Thới', 29),
('Phường Hòa Bình', 29),
('Phường Tân Tạo', 29),
('Phường Bình Tân', 29),
('Phường Bình Trị Đông', 29),
('Phường Bình Hưng Hòa', 29),
('Phường Gia Định', 29),
('Phường Bình Thạnh', 29),
('Phường Bình Lợi Trung', 29),
('Phường Thạnh Mỹ Tây', 29),
('Phường Đức Nhuận', 29),
('Phường Cầu Kiệu', 29),
('Phường Phú Nhuận', 29),
('Phường Tân Sơn Hòa', 29),
('Phường Tân Sơn Nhất', 29),
('Phường Tân Hòa', 29),
('Phường Bảy Hiền', 29),
('Ph30', 29),
('Phường Long Phước', 29),
('Phường Long Trường', 29),
('Phường Cát Lái', 29),
('Phường Bình Trưng', 29),
('Phường Phước Long', 29),
('Phường An Khánh', 29),
('Xã Vĩnh Lộc', 29),
('Xã Tân', 29),
('Xã Cần Giờ', 29),
('Xã Củ Chi', 29),
('Xã Tân An Hội', 29),
('Xã Thái Mỹ', 29),
('Xã An Nhơn Tây', 29),
('Xã Nhuận Đức', 29),
('Xã Phú Hòa Đông', 29),
('Xã Bình Mỹ', 29),
('Xã Đông Thạnh', 29),
('Xã Hóc Môn', 29),
('Xã Xuân Thới Sơn', 29),
('Xã Bình Châu', 29),
('Phường Thới Hòa', 29),
('Xã Thạnh An', 29),
('Xã Long Hồ', 30),
('Xã Phú Quới', 30),
('Phường Thanh Đức', 30),
('Phường Long Châu', 30),
('Phường Phước Hậu', 30),
('Phường Tân Hạnh', 30),
('Phường Tân Ngãi', 30),
('Xã Lục Sỹ Thành', 30),
('Xã Trà Ôn', 30),
('Xã Trà Côn', 30),
('Xã Vĩnh Xuân', 30),
('Xã Hòa Bình', 30),
('Xã Hòa Hiệp', 30),
('Xã Tam Bình', 30),
('Phường Cái Vồn', 30),
('Phường Đông Thành', 30),
('Phường Long Đức', 30),
('Phường Trà Vinh', 30),
('Phường Nguyệt Hóa', 30),
('Phường Hòa Thuận', 30),
('Xã An Trường', 30),
('ỉnh Vĩnh Long', 30),
('Xã Long Hòa', 30),
('Xã Cầu Kè', 30),
('Xã Phong Thạnh', 30),
('Xã An Phú Tân', 30),
('Xã Tam Ngãi', 30),
('Xã Tân Hòa', 30),
('Xã Hùng Hòa', 30),
('Xã Lưu Nghiệp Anh', 30),
('Xã Đại An', 30),
('Xã Hàm Giang', 30),
('Xã Trà Cú', 30),
('Xã Long Hiệp', 30),
('Xã Tập Sơn', 30),
('Phường Duyên Hải Phường An Hội', 30),
('Phường Phú Khương', 30),
('Phường Bến Tre', 30),
('Phường Sơn Đông', 30),
('Phường Phú Tân', 30),
('Xã Phú Túc', 30),
('Xã Giao Long', 30),
('Xã Tiên Th Bình', 30),
('Xã Nhuận Phú Tân', 30),
('Xã Đồng Khởi', 30),
('Xã Mỏ Cày', 30),
('Xã Thành Thới', 30),
('Xã An Định', 30),
('Xã Hương Mỹ', 30),
('Xã Đại Điền Vĩnh Long', 30),
('Xã Ba Tri', 30),
('Xã Tân Xuân', 30),
('Xã Mỹ Chánh Hòa', 30),
('Xã An Ngãi Trung', 30),
('Xã An Hiệp', 30),
('Xã Hưng Nhượng', 30),
('Xã Giồng Trôm Tỉnhĩnh Long', 30),
('Xã Bình Đại', 30),
('Xã Thạnh Trị', 30),
('Xã Lộc Thuận', 30),
('Xã Châu Hưng', 30),
('Xã Phú Thuận', 30),
('Phường Long Thuận', 31),
('Phường Sơn Qui', 31),
('Phường Bình Xuân', 31),
('Phường Mỹ Phước Tây', 31),
('Phường Thanh Hòa', 31),
('Phường Cai Lậy', 31),
('Phường Nhị Quý Tỉnh567', 31),
('Xã Ngũ Hiệp', 31),
('Xã Long Tiên', 31),
('Xã Mỹ Thành', 31),
('Xã Thạnh Phú', 31),
('Xã Tân Phước 1', 31),
('Xã Tân Phước 2', 31),
('Xã Tân Phước 3 Tỉnh70', 31),
('Xã Bình Trưng', 31),
('Xã Mỹ Tịnh An', 31),
('Xã Lương Hòa Lạc', 31),
('Xã Tân Thuận Bình', 31),
('Xã Chợ Gạo', 31),
('Xã An Thạnh Thủy', 31),
('Xã Bình Ninh Tỉnh Đồng', 31),
('Xã Tân Hòa', 31),
('Xã Tân Đông', 31),
('Xã Gia Thuận', 31),
('Xã Tân Thới', 31),
('Xã Tân Phú Đông', 31),
('Xã Tân Hồng', 31),
('Xã Tân Thành', 31),
('X Long Phú Thuận', 31),
('Xã An Hòa', 31),
('Xã Tam Nông', 31),
('Xã Phú Thọ', 31),
('Xã Tràm Chim', 31),
('Xã Phú Cường', 31),
('Xã An Long', 31),
('Xã Thanh Bình T Đồng Tháp', 31),
('Xã Trường Xuân', 31),
('Xã Phương Thịnh', 31),
('Xã Phong Mỹ', 31),
('Xã Ba Sao', 31),
('Xã Mỹ Thọ', 31),
('Xã Bình Hàng Trung', 31),
('Xã Mỹ Hiệp [ Xã Phú Hựu', 31),
('Xã Tân Nhuận Đông', 31),
('Xã Tân Phú Trung', 31),
('Xã Mỹ Hòa Hưng Tỉnh An Giang Thạnh Đông', 32),
('Xã Chợ Vàm', 32),
('Xã Hòa Lạc', 32),
('Xã Phú Lâm', 32),
('Xã Châu Phú', 32),
('Xã Mỹ Đức', 32),
('Xã Vĩnh Thạnh Trung', 32),
('Xã Bình Mỹ [58 Trạch', 32),
('Xã Tây Phú', 32),
('Xã Vĩnh Bình', 32),
('Xã Vĩnh Thuận', 32),
('Xã Vĩnh Phong', 32),
('Xã Vĩnh Hòa', 32),
('Xã U Minh Thượng', 32),
('Xã Đông Hòa', 32),
('Xã Gò Quao', 32),
('Xã Vĩnh Hòa Hưng', 32),
('Xã Vĩnh Tuy', 32),
('Xã Giồng Riềng', 32),
('Xã Thạnh Hưng', 32),
('Xã Long Thạnh', 32),
('Xã Hòa Hưng [594 An Giang', 32),
('Xã Giang Thành', 32),
('Xã Vĩnh Điều', 32),
('Xã Hòa Điền', 32),
('Xã Kiên Lương', 32),
('Xã Sơn Hải', 32),
('Xã Hòn Nghệ', 32),
('Đặc khu Kiên Hải Tỉnh An Giang CẦN THƠ', 32),
('Phường Ninh Kiều', 33),
('Phường Cái Khế', 33),
('Phường Tân An', 33),
('Phường An Bình', 33),
('Ph Phước Thới', 33),
('Phường Trung Nhứt', 33),
('Phường Thốt Nốt', 33),
('Phường Thuận Hưng', 33),
('Phường Tân Lộc', 33),
('Xã Phong Điền', 33),
('Xã Nhơn Ái', 33),
('Phú', 33),
('Xã Thới Hưng', 33),
('Xã Trung Hưng', 33),
('Xã Vĩnh Thạnh', 33),
('Xã Vĩnh Trinh', 33),
('Xã Thạnh An', 33),
('Xã Thạnh Quới', 33),
('Xã', 33),
('Xã Vĩnh Viễn', 33),
('Xã Xà Phiên', 33),
('Xã Lương Tâm', 33),
('Phường Long Bình', 33),
('Phường Long Mỹ', 33),
('Phường Long Phú 1', 33),
('Xã Thạnh Xuân [6* Xã Tân Bình', 33),
('Xã Hòa An', 33),
('Xã Phương Bình', 33),
('Xã Tân Phước Hưng', 33),
('Xã Hiệp Hưng', 33),
('Xã Phụng Hiệp', 33),
('Xã Thạnh Hòa', 33),
('Phường Cần Thơ', 33),
('Xã Đại Ngãi', 33),
('Xã Tân Thạnh', 33),
('Xã Long Phú', 33),
('Xã Nhơn Mỹ', 33),
('Xã Phong Nẫm', 33),
('Xã An Lạc Thôn', 33),
('Xã Kế Sách Tp C7', 33),
('Xã Long Hưng', 33),
('Xã Mỹ Phước', 33),
('Xã Mỹ Hương', 33),
('Xã Vĩnh Hải', 33),
('Xã Lai Hòa', 33),
('Phường Vĩnh Phước', 33),
('Phường Vĩnh Châu', 33),
('Thới An', 33),
('Xã Tài Văn', 33),
('Xã Liêu Tú', 33),
('Xã Lịch Hội Thượng', 33),
('Xã Trần Đề', 33),
('Xã An Thạnh', 33),
('Xã Cù Lao Dung', 33),
('Xã Tân Tiến', 34),
('Xã Tạ An Khương', 34),
('Xã Trần Phán', 34),
('Xã Thanh Tùng', 34),
('Xã Đầm Dơi', 34),
('Xã Quách Phẩm', 34),
('Xã Cái Đôi V', 34),
('Phường Bạc Liêu', 34),
('Phường Vĩnh Trạch', 34),
('Xã Vĩnh Lộc', 34),
('Xã Ninh Thạnh Lợi', 34),
('Xã Ninh Quới', 34),
('Xã Hòa Bình', 34);