INSERT INTO tinh (id, ten_tinh) VALUES
(01, 'THÀNH PHỐ HÀ NỘI'),
(02, 'TỈNH BẮC NINH'),
(03, 'TỈNH QUẢNG NINH'),
(04, 'THÀNH PHỐ HẢI PHÒNG'),
(05, 'TỈNH HƯNG YÊN'),
(06, 'TỈNH NINH BÌNH'),
(07, 'TỈNH CAO BẰNG'),
(08, 'TỈNH TUYÊN QUANG'),
(09, 'TỈNH LÀO CAI'),
(10, 'TỈNH THÁI NGUYÊN'),
(11, 'TỈNH LẠNG SƠN'),
(12, 'TỈNH PHÚ THỌ'),
(13, 'TỈNH ĐIỆN BIÊN'),
(14, 'TỈNH LAI CHÂU'),
(15, 'TỈNH SƠN LA'),
(16, 'TỈNH THANH HÓA'),
(17, 'TỈNH NGHỆ AN'),
(18, 'TỈNH HÀ TĨNH'),
(19, 'TỈNH QUẢNG TRỊ'),
(20, 'THÀNH PHỐ HUẾ'),
(21, 'THÀNH PHỐ ĐÀ NẴNG'),
(22, 'TỈNH QUẢNG NGÃI'),
(23, 'TỈNH KHÁNH HÒA'),
(24, 'TỈNH GIA LAI'),
(25, 'TỈNH ĐẮK LẮK'),
(26, 'TỈNH LÂM ĐỒNG'),
(27, 'TỈNH TÂY NINH'),
(28, 'TỈNH ĐỒNG NAI'),
(29, 'THÀNH PHỐ HỒ CHÍ MINH'),
(30, 'TỈNH VĨNH LONG'),
(31, 'TỈNH ĐỒNG THÁP'),
(32, 'TỈNH AN GIANG'),
(33, 'THÀNH PHỐ CẦN THƠ'),
(34, 'TỈNH CÀ MAU');
